cars = [
    "corolla",
    "hilux",
    "ferrari",
    "fortuner",
    "sorento",
    "tucson",
    "pajero",
    "picanto",
    "audi",
    "prado",
    "tesla",
    "porsche",
    "mercedes",
    "bmw",
    "volkswagen",
    "renault",
    "peugeot",
    "fiat",
    "volvo",
    "jaguar",
    "land rover",
]


tech_companies = [
    "apple",
    "google",
    "microsoft",
    "samsung",
    "xiaomi",
    "oneplus",
    "oppo",
    "vivo",
    "realme",
    "motorola",
    "huawei",
    "dell",
    "sony",
    "asus",
    "accer",
    "lenovo",
    "nokia",
    "logitech",
]

countries = [
    "afghanistan",
    "algeria",
    "argentina",
    "australia",
    "bangladesh",
    "belgium",
    "brazil",
    "canada",
    "china",
    "england",
    "denmark",
    "egypt",
    "france",
    "germany",
    "india",
    "turkey",
    "italy",
    "japan",
    "kenya",
    "malaysia",
    "mexico",
    "morocco",
    "nigeria",
    "pakistan",
    "poland",
    "portugal",
    "qatar",
    "russia",
    "spain",
    "switzerland",
    "turkey",
]

social_media = [
    "facebook",
    "youtube",
    "whatsapp",
    "instagram",
    "twitter",
    "snapchat",
    "pinterest",
    "reddit",
    "discord",
    "tiktok",
    "telegram",
    "discord",
]
